spring:
  mvc:
    view:
      # JSP
      prefix: /WEB-INF/views/
      suffix: .jsp
#  profiles:
#    active: db, jwt, cd, oauth2, bucket, mail, chatbot
  datasource:
    # DB
    url: ENC(JIgNebx3D3Q39lxU1GOsFvdjYUfjOUKLGmnBRl/tXyVQEhTRnA4aQIqd3q5eCpYrSmomSucoMFs8z5Stu0JMwnMIUdbebdctV6F6TIo9Y2Jnei0Y4YiiiptUT24LW9y9YHi1R6J8tNjswYK2oUHqQ9ij8w9ZjgJjn7eAQI83I48=)
    username: ENC(G52N7IEZx0X1BwTBi7MyUCIjh5kp9YBK)
    password: ENC(qEwlb7/UowHwGLD3QF+KktT19PNW9ON2)
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # aws
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

  # oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(RVqLmMPE/G24ZSlWOpOE47hjnH1zGofWjXNjkjx55zGJnNkxXtAs4K69jTr56iYIU1nfbQCOBtQmE2bvdD9zbNabjly9YQSJuidPq4N2WfbjoYuoHQOu9A==)
            client-secret: ENC(9BZcVWaRj7xkEmg/5wUGUu5HaAKMTa1CnHnaqK8G/Wbp+EVxnHyXhMkLEJdcs4Zz)
            scope: profile, email
          naver:
            client-id: ENC(fgrwPAAkg9upSD51Ok+utdtlg919Oom658OVFgF3TDE=)
            client-secret: ENC(/PmnnK1Y5u37cmRJRJJ9DEbLz/iOJ0Ye)
            redirect-uri: http://223.130.161.96:3000/oauth/redirected/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

# JWT
jwt:
  issuer: ENC(bRAbZ8L8yp2ki4M+I9GeYw==)
  secret_key: ENC(pk6TbLK5FGF08XE0uBtzkT0VZvROjEwT)

# Email
mail:
  from_email: ENC(qQ95E2jP4jfpZX4vWKa4yt9/Gv+qwXqY30WelVg/hNk=)
  email_password: ENC(4FeUU2axKF1bwp/hjp7hLjCvOIewSLtN7kbJo89JZvE=)

# MyBatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

# s3 bucket
cloud:
  aws:
    credentials:
      access-key: ENC(IIVmrqyFpiSGxkVMiscEC2xhU9B6+eaiGkS7shW+BuA=)
      secret-key: ENC(xsXs12PyKEDZuNlLyARrs8YHgN2UgPIqI5e6e1+PU0BdGa9Pi0pjfVz728dbDlGvF5KKzVfCr7c=)
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      #      endpoint: s3.ap-northeast-2.amazonaws.com
      chat-bucket: ENC(cqPFZ3cK8TpD7IA4DXLQAlgxbdMDtfIO)
      and-bucket: ENC(z22eXRTSRHtRTqK7pzmqQNwGNTV/7IrD)
      crowd-bucket: ENC(CYHKcMKdxfMd9I2PZf3XEDr9ewIvQt2c)
      user-bucket: ENC(MrWbx88VfU4frjEzspU3QspW0c4EToIy)

# clova chatbot
chatbot:
  secretKey: ENC(HGCYnk4nkN5AboLS88bsPDiJ9HOo1Q0djMhIdENGSUrJFongwRwzbUl9O987WBim/a0S86xHPig=)
  apiUrl: ENC(ggWickNetkv7iRX6MjatxmXjMHX4NoeKE8d49pDNxobgJ8xcV3L+9VR1FrfNfwCNNQZTqdpaMwfisArA6ihlk6b/W6IllCR/7QGboyHEoCzdCZRO/Pmk1fQSzqTrucuzJLIqwvWVQjaAz8T2fYdYHHFqTKHctFfa6oHC5+ZTTH0=)

# Jaspyt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor