spring:
  mvc:
    view:
      # JSP
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: db, jwt, cd
  datasource:
    # DB
    url: ${url}
    username: ${usrname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # aws
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

# JWT
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}

#MyBatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

# s3 bucket
cloud:
  aws:
    credentials:
      access-key: ${access}
      secret-key: ${secret}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    s3:
      endpoint: https://kr.object.ncloudstorage.com
#      endpoint: s3.ap-northeast-2.amazonaws.com
      chat-bucket: ${chat-bucket}
      and-bucket: ${and-bucket}

# Server Auto Reload
#server:
#  devtools:
#    liverload:
#      enabled: true
#    restart:
#      enabled: true