spring:
  mvc:
    view:
      # JSP
      prefix: /WEB-INF/views/
      suffix: .jsp
  profiles:
    active: db, jwt, cd, oauth2
  datasource:
    # DB
    url: ${url}
    username: ${usrname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${client-id}
            client-secret: ${client-secret}
            redirect-uri: ${redirect-uri}
            client-name: ${client-name}
            authorization-grant-type: ${authorization-grant-type}
            scope: ${scope}

# JWT
jwt:
  issuer: ${issuer}
  secret_key: ${secret_key}

# Oauth2


#MyBatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml

# Server Auto Reload
#server:
#  devtools:
#    liverload:
#      enabled: true
#    restart:
#      enabled: true